services:
  proxyserver:
    image: interop-proxy-server:1.0.0-SNAPSHOT
    environment:
      - INTEROP_TENANT_CONFIG=file:/config/tenants.yaml
      - SPRING_DATASOURCE_URL=jdbc:mysql://queue:secret@db:3306/interop
      - AO_SANDBOX_KEY=${AO_SANDBOX_KEY}
    volumes:
      - ./src/it/resources/:/config
    ports:
      - 8080:8080
    depends_on:
      - liquibase
      - db
  db:
    image: mysql/mysql-server
    container_name: db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: interop
      MYSQL_USER: queue
      MYSQL_PASSWORD: secret
  liquibase:
    container_name: liquibase
    image: interop-queue-liquibase
    environment:
      - JDBC_URL=jdbc:mysql://queue:secret@db:3306/interop
    depends_on:
      - db

