apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "interop-proxy-server.fullname" . }}-config
data:
  K8S_ENV: "{{ .Values.infra.env }}"
  ROLLBAR_ENDPOINT: "http://rollbar.com"
  DD_SERVICE: "{{ include "interop-proxy-server.fullname" . }}"
