apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "interop-proxy-server.fullname" . }}
  labels:
    app: {{ template "interop-proxy-server.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "interop-proxy-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "interop-proxy-server.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      annotations:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ template "interop-proxy-server.fullname" . }}
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/node
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ template "interop-proxy-server.fullname" . }}
      containers:
        - name: interop-proxy-server
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - containerPort: 80
          env:
            {{- include "interop-proxy-server.env" . | nindent 10 }}
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ping
              scheme: HTTP
              port: 80
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ping
              scheme: HTTP
              port: 80
            timeoutSeconds: 2
      restartPolicy: Always
