name: Build and push to Nexus; Deploy to ArgoCD DEV

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ main ]

jobs:
  image-push-latest:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Push Docker:latest to Nexus
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./
      image-tag: latest
      repo: "interop-proxy-server"
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  image-push-sha:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Push Docker:SHA to Nexus
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./
      image-tag: ${{ github.sha }}
      repo: "interop-proxy-server"
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  argocd_dev:
    uses: projectronin/github/.github/workflows/argocd_deploy.yml@master
    needs: [ image-push-sha ]
    with:
      environment: dev
      image-tag: ${{ github.sha }}
    secrets:
      argocd-svc-automation: ${{ secrets.ARGOCD_SVC_AUTOMATION }}
